spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://thesimsdb-test.cnyqegjgetrv.us-east-2.rds.amazonaws.com/booking-g5-test
    username: admin
    password: administrador
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt.secret: jwtgrupo5
    jwt.expiration: 36000
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: digitalbooking.grupo05@gmail.com
    password: qqgedualkrmuilkm
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

